In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
import seaborn as sns

In [4]:
import matplotlib.pyplot as plt

In [5]:
dataset = pd.read_csv('house-prediction.csv')

In [6]:
categorical_feature_nan = [ feature for feature in dataset.columns if dataset[feature].isnull().sum()>1 and dataset[feature].dtype=='O']

In [7]:
for feature in categorical_feature_nan:
    print("{} : {}%".format(feature,np.round(dataset[feature].isnull().mean(),4)))

Alley : 0.9377%
MasVnrType : 0.0055%
BsmtQual : 0.0253%
BsmtCond : 0.0253%
BsmtExposure : 0.026%
BsmtFinType1 : 0.0253%
BsmtFinType2 : 0.026%
FireplaceQu : 0.4726%
GarageType : 0.0555%
GarageFinish : 0.0555%
GarageQual : 0.0555%
GarageCond : 0.0555%
PoolQC : 0.9952%
Fence : 0.8075%
MiscFeature : 0.963%

In [8]:
for feature in categorical_feature_nan:
    dataset[feature]=dataset[feature].fillna("Missing")

In [9]:
dataset.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,Missing,Reg,Lvl,AllPub,...,0,Missing,Missing,Missing,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,Missing,Reg,Lvl,AllPub,...,0,Missing,Missing,Missing,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,Missing,IR1,Lvl,AllPub,...,0,Missing,Missing,Missing,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,Missing,IR1,Lvl,AllPub,...,0,Missing,Missing,Missing,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,Missing,IR1,Lvl,AllPub,...,0,Missing,Missing,Missing,0,12,2008,WD,Normal,250000

In [10]:
numerical_nan = [feature for feature in dataset.columns if dataset[feature].isnull().sum()>1 and dataset[feature].dtypes!='O']

In [11]:
numerical_nan

['LotFrontage', 'MasVnrArea', 'GarageYrBlt']

In [12]:
for feature in numerical_nan:
    print("{} : {}%".format(feature,np.round(dataset[feature].isnull().mean(),4)))

LotFrontage : 0.1774%
MasVnrArea : 0.0055%
GarageYrBlt : 0.0555%

In [14]:
for feature in numerical_nan:
    median_value=dataset[feature].median()
    dataset[feature+'nan']=np.where(dataset[feature].isnull(),1,0)
    dataset[feature]=dataset[feature].fillna(median_value,inplace=True)

In [15]:
dataset

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,LotFrontagenan,MasVnrAreanan,GarageYrBltnan
0,1,60,RL,None,8450,Pave,Missing,Reg,Lvl,AllPub,...,Missing,0,2,2008,WD,Normal,208500,0,0,0
1,2,20,RL,None,9600,Pave,Missing,Reg,Lvl,AllPub,...,Missing,0,5,2007,WD,Normal,181500,0,0,0
2,3,60,RL,None,11250,Pave,Missing,IR1,Lvl,AllPub,...,Missing,0,9,2008,WD,Normal,223500,0,0,0
3,4,70,RL,None,9550,Pave,Missing,IR1,Lvl,AllPub,...,Missing,0,2,2006,WD,Abnorml,140000,0,0,0
4,5,60,RL,None,14260,Pave,Missing,IR1,Lvl,AllPub,...,Missing,0,12,2008,WD,Normal,250000,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,None,7917,Pave,Missing,Reg,Lvl,AllPub,...,Missing,0,8,2007,WD,Normal,175000,0,0,0
1456,1457,20,RL,None,13175,Pave,Missing,Reg,Lvl,AllPub,...,Missing,0,2,2010,WD,Normal,210000,0,0,0
1457,1458,70,RL,None,9042,Pave,Missing,Reg,Lvl,AllPub,...,Shed,2500,5,2010,WD,Normal,266500,0,0,0
1458,1459,20,RL,None,9717,Pave,Missing,Reg,Lvl,AllPub,...,Missing,0,4,2010,WD,Normal,142125,0,0,0
1459,1460,20,RL,None,9937,Pave,Missing,Reg,Lvl,AllPub,...,Missing,0,6,2008,WD,Normal,147500,0,0,0

In [35]:
num_feature = [feature for feature in dataset.columns if dataset[feature].isnull().sum()==0 and dataset[feature].dtype!='Object']
num_feature

['Id',
 'MSSubClass',
 'MSZoning',
 'LotArea',
 'Street',
 'Alley',
 'LotShape',
 'LandContour',
 'Utilities',
 'LotConfig',
 'LandSlope',
 'Neighborhood',
 'Condition1',
 'Condition2',
 'BldgType',
 'HouseStyle',
 'OverallQual',
 'OverallCond',
 'YearBuilt',
 'YearRemodAdd',
 'RoofStyle',
 'RoofMatl',
 'Exterior1st',
 'Exterior2nd',
 'MasVnrType',
 'ExterQual',
 'ExterCond',
 'Foundation',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinSF1',
 'BsmtFinType2',
 'BsmtFinSF2',
 'BsmtUnfSF',
 'TotalBsmtSF',
 'Heating',
 'HeatingQC',
 'CentralAir',
 '1stFlrSF',
 '2ndFlrSF',
 'LowQualFinSF',
 'GrLivArea',
 'BsmtFullBath',
 'BsmtHalfBath',
 'FullBath',
 'HalfBath',
 'BedroomAbvGr',
 'KitchenAbvGr',
 'KitchenQual',
 'TotRmsAbvGrd',
 'Functional',
 'Fireplaces',
 'FireplaceQu',
 'GarageType',
 'GarageFinish',
 'GarageCars',
 'GarageArea',
 'GarageQual',
 'GarageCond',
 'PavedDrive',
 'WoodDeckSF',
 'OpenPorchSF',
 'EnclosedPorch',
 '3SsnPorch',
 'ScreenPorch',
 'PoolArea',
 'PoolQC',
 'Fence',
 'MiscFeature',
 'MiscVal',
 'MoSold',
 'YrSold',
 'SaleType',
 'SaleCondition',
 'SalePrice',
 'LotFrontagenan',
 'MasVnrAreanan',
 'GarageYrBltnan']

In [36]:
dataset.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,LotFrontagenan,MasVnrAreanan,GarageYrBltnan
0,1,60,RL,None,8450,Pave,Missing,Reg,Lvl,AllPub,...,Missing,0,2,2008,WD,Normal,208500,0,0,0
1,2,20,RL,None,9600,Pave,Missing,Reg,Lvl,AllPub,...,Missing,0,5,2007,WD,Normal,181500,0,0,0
2,3,60,RL,None,11250,Pave,Missing,IR1,Lvl,AllPub,...,Missing,0,9,2008,WD,Normal,223500,0,0,0
3,4,70,RL,None,9550,Pave,Missing,IR1,Lvl,AllPub,...,Missing,0,2,2006,WD,Abnorml,140000,0,0,0
4,5,60,RL,None,14260,Pave,Missing,IR1,Lvl,AllPub,...,Missing,0,12,2008,WD,Normal,250000,0,0,0

## Handlin rare categorical Feature

In [37]:
categorical_feature = [feature for feature in dataset.columns if dataset[feature].dtype=='O']

In [38]:
categorical_feature

['MSZoning',
 'LotFrontage',
 'Street',
 'Alley',
 'LotShape',
 'LandContour',
 'Utilities',
 'LotConfig',
 'LandSlope',
 'Neighborhood',
 'Condition1',
 'Condition2',
 'BldgType',
 'HouseStyle',
 'RoofStyle',
 'RoofMatl',
 'Exterior1st',
 'Exterior2nd',
 'MasVnrType',
 'MasVnrArea',
 'ExterQual',
 'ExterCond',
 'Foundation',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'Heating',
 'HeatingQC',
 'CentralAir',
 'Electrical',
 'KitchenQual',
 'Functional',
 'FireplaceQu',
 'GarageType',
 'GarageYrBlt',
 'GarageFinish',
 'GarageQual',
 'GarageCond',
 'PavedDrive',
 'PoolQC',
 'Fence',
 'MiscFeature',
 'SaleType',
 'SaleCondition']

In [42]:
for feature in categorical_feature:
    temp = dataset.groupby(feature)['SalePrice'].count()/len(dataset)
    temp_df=temp[temp>0.01].index
    dataset[feature]=np.where(dataset[feature].isin(temp_df),dataset[feature],'Rare')

In [43]:
dataset.head(100)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,LotFrontagenan,MasVnrAreanan,GarageYrBltnan
0,1,60,Rare,Rare,8450,Rare,Rare,Rare,Rare,Rare,...,Rare,0,2,2008,Rare,Rare,208500,0,0,0
1,2,20,Rare,Rare,9600,Rare,Rare,Rare,Rare,Rare,...,Rare,0,5,2007,Rare,Rare,181500,0,0,0
2,3,60,Rare,Rare,11250,Rare,Rare,Rare,Rare,Rare,...,Rare,0,9,2008,Rare,Rare,223500,0,0,0
3,4,70,Rare,Rare,9550,Rare,Rare,Rare,Rare,Rare,...,Rare,0,2,2006,Rare,Rare,140000,0,0,0
4,5,60,Rare,Rare,14260,Rare,Rare,Rare,Rare,Rare,...,Rare,0,12,2008,Rare,Rare,250000,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,60,Rare,Rare,9765,Rare,Rare,Rare,Rare,Rare,...,Rare,480,4,2009,Rare,Rare,185000,1,0,0
96,97,20,Rare,Rare,10264,Rare,Rare,Rare,Rare,Rare,...,Rare,0,8,2006,Rare,Rare,214000,0,0,0
97,98,20,Rare,Rare,10921,Rare,Rare,Rare,Rare,Rare,...,Rare,0,5,2007,Rare,Rare,94750,0,0,0
98,99,30,Rare,Rare,10625,Rare,Rare,Rare,Rare,Rare,...,Rare,400,5,2010,Rare,Rare,83000,0,0,0
99,100,20,Rare,Rare,9320,Rare,Rare,Rare,Rare,Rare,...,Rare,400,1,2010,Rare,Rare,128950,0,0,1

2.5